### ISSUE TITLE
Swift 6 Concurrency issue 

### ISSUE THREAD

**Issue by hammas1993** [AzureAD/microsoft-authentication-library-for-objc#2474]
After switching to swift 6 app crashes on msalApplication.acquireTokenSilent(with: parameters)....!

**Comment by kaisong1990** [comment]
Hi @hammas1993 can you please share some sample code and crash logs? Thanks

**Comment by hammas1993** [comment]
msalApplication.acquireTokenSilent(with: parameters)
            { (result, error) in
            }
            using this func in swift 6 creates this crash and if i remove the func the error doesn't occur 
            
<img width="1495" alt="Screenshot 2025-01-12 at 6 46 10 PM" src="https://github.com/user-attachments/assets/56a66dc4-9557-4513-a840-b6aaa4635e37" />

**Comment by kaisong1990** [comment]
Thanks for reporting, the issue was fixed in dev branch and will be shipped in our next release (ETA end of Feb)

**Comment by techios056** [comment]
I'm having the similar crash while configuring self.application = try MSALPublicClientApplication(configuration: pcaConfig).

![Image](https://github.com/user-attachments/assets/cbc7661f-eaf9-46a0-824f-7d9629a75ba1)

Is there a workaround? As its not using either @Sendable or @escaping to handle concurrency. I have tried using async call and updated to latest MSAL version (1.9.0) but nothing is working. Adding the screenshot for the crash below: -

![Image](https://github.com/user-attachments/assets/0320b2c0-3bad-49b8-9a26-ab4af6b2f398)

Thanks in advance!

**Comment by stack** [comment]
I am seeing similar crashes when enabling Swift 6 language mode and Approachable Concurrency.

I've verified that `MSALPublicClientApplication` is being created on the main thread, which then dispatches internally and crashes, as shown in the issue above.

There is no crash with Swift 5 language mode and Approachable Concurrency.

**Comment by stack** [comment]
This still occurs with 2.10.0. Xcode 26.4.

<img width="1440" height="503" alt="Image" src="https://github.com/user-attachments/assets/d85f51bf-bbaa-4feb-9cca-a6da17e89736" />

**Comment by stack** [comment]
Here is a sample app that crashes in the same way.

This is a new project created with Xcode 26.4. Swift language mode is set to Swift 6.

Edit the `ContentView.swift` file with proper values and run to crash.

[MSALCrash.zip](https://github.com/user-attachments/files/26510305/MSALCrash.zip)

**Comment by kaisong1990** [comment]
Hi @stack , thanks for sharing the sample project. We’re currently investigating the issue and potential fixes. In the meantime, could you please try adding @Sendable to avoid the crash?

e.g.
```
        MSALGlobalConfig.loggerConfig.setLogCallback { @Sendable level, message, containsPII in
            print("\(level): \(message)")
        }
```

**Comment by stack** [comment]
@kaisong1990 This does fix the crash. Thank you!
